### ISSUE TITLE
Blob download on iOS not working

### ISSUE THREAD

**Issue by ben04** [DanielHabenicht/ngx-vcard#89] opened 2019-06-06 13:41 UTC
Hi,

when I try to download the vCard I created with this library on an iPhone, it doesn't work.
Safari gives the following error message:
"The operation couldn’t be completed. (WebKitBlobResource error 1.)"
On Chrome I just get a "website not reachable" error, the url begins with 'blob:https://'...
On Firefox it's just trying to load the "new page" forever. Nothing happens here.

Any hint how to fix that? Appreciate any help :)

**Comment by DanielHabenicht** [comment] 2019-06-07 07:20
Hi, are all issues just present on mobile browsers on smartphones?

**Comment by ben04** [comment] 2019-06-07 16:23
Yes, it happens just on iPhones and iPads.

**Comment by DanielHabenicht** [comment] 2019-06-07 18:00
Seems like this is the Bug you are having: https://stackoverflow.com/a/56002172/9277073 

There is nothing wrong with the code used by this library. 

I even tried using the [file-saver](https://github.com/eligrey/FileSaver.js) package but it does not solve the problem either.

**Comment by ben04** [comment] 2019-06-08 11:49
It also happens on Firefox and Chrome on iPhones/iPads, so I'm not sure...maybe iOS handles blob as too dangerous in general and prevents a download.

**Comment by DanielHabenicht** [comment] 2019-06-08 12:49
Yep, MacOS handles it like any other operating system. Only iOS produces such errors. 

As I can't reproduce the Bug, because I don't have an iOS device at my hand I can only wish you luck to catch the error. 

I would be happy if you report back a solution if you find one.

**Comment by DanielHabenicht** [comment] 2019-08-12 21:28
@ben04 is the bug only occurring if you pin the tab? Is it working if you unpin the tab?

**Comment by DanielHabenicht** [comment] 2020-09-24 12:14
@ben04 any updates ony your side? 

I will close this issue as it has nothing to do with this package.

**Closed by DanielHabenicht** 2020-09-24 12:14 UTC

**Comment by MrEduar** [comment] 2021-04-05 19:23
Maybe it can be related to this.
https://discussions.apple.com/thread/7702312
https://discussions.apple.com/thread/251757033
