### ISSUE TITLE
UTF-8 in socialUrls

### ISSUE THREAD

**Issue by rendonvelez** [DanielHabenicht/ngx-vcard#205] opened 2020-01-13 04:55 UTC
in socialUrls urls are not visible when the econding is UTF-8

**Comment by DanielHabenicht** [comment] 2020-01-13 13:47
Can you post a code snippet on what you are using?

**Comment by DanielHabenicht** [comment] 2020-01-14 10:57
Without an reproduction I can't fix the bug.

**Comment by DanielHabenicht** [comment] 2020-09-24 12:14
Closing because of missing reproduction. Also seems to be tracked partly here #36.

**Closed by DanielHabenicht** 2020-09-24 12:14 UTC
